### ISSUE TITLE
DB 설정

### ISSUE THREAD

**Issue by RokwonK** [Nexters/keyme-backend#13]
### Description
DB 설정 및 회원가입 로직 연동

### Tasks
- [ ] 설정 내 DB 연동
- [ ] Member 기본 테이블 추가
- [ ] Member Entity 추가
- [ ] Member Repository 추가
- [ ] 기존 Service에 회원가입 로직 추가
