### ISSUE TITLE
멤버 관련 도메인 엔티티 정의 및 기능 구현

### ISSUE THREAD

**Issue by street62** [Nexters/keyme-backend#32]
### Description
멤버 관련 도메인 엔티티를 정의하고, 관련 API 기능을 구현합니다. (통계 제외)

### Tasks
- [x] 멤버 엔티티 및 도메인 객체 정의
- [x] Member 컨트롤러 및 DTO 정의
- [x] 통계처리 제외 API 구현

**Comment by RokwonK** [comment]
이거 클로즈 시킬까요?

**Comment by RokwonK** [comment]
그 PR 올릴때 아래 코드를 PR 내용에 포함하면 merge 시 이슈도 같이 닫힙니다!
| close #{이슈번호}

**Comment by street62** [comment]
오호 감사합니다! 다음 피알부터 적용해볼게요!-!
이 이슈는 멤버 프로필 사진 쪽 구현하고 닫겠습니당
