### ISSUE TITLE
test 클라이언트 테스트 개발에 필요한 데이터 초기화 API 만들기

### ISSUE THREAD

**Issue by RokwonK** [Nexters/keyme-backend#41]
### Description
온보딩 테스트, 데일리 테스트, 테스트 제출과 관련된 가짜 데이터들을 생성.
API로 간단하게 데이터들을 초기화할 수 있도록 만들기

### Tasks
- [ ] 온보딩, 데일리 테스트를 위한 가짜 질문들 push
- [ ] 해당 값들을 테스트 후 초기화 할 수 있도록 API 만들기(AMDIN 권한으로만 가능하게!)
- [ ] security 경로 열어두기
