### ISSUE TITLE
이미지 업로드 시 제약조건 정의

### ISSUE THREAD

**Issue by street62** [Nexters/keyme-backend#45]
### Description
프로필 이미지 업로드 시 제약조건 관련한 논의 후 적용이 필요합니다.

### Tasks
- [ ] Multipart 업로드 시 이미지 형식 제한
- [ ] 서버로 들어올 수 있는 image 최대 파일 크기/해상도
- [ ] 리사이징 파일 크기/해상도
