### ISSUE TITLE
멤버 State 정의 및 전역 예외 정리

### ISSUE THREAD

**Issue by street62** [Nexters/keyme-backend#46]
### Description
- Member 도메인 로직 중 발생하는 State 응답 등을 처리하고, 전역 예외 관련 핸들러를 개선합니다.

### Tasks
- [ ] Member 수정 시 State 정의
- [ ] 이미지 파일 업로드 실패 시 Exception 정의
- [ ] 전역 예외 핸들러 ApiResponse 사용하도록 변경
