### ISSUE TITLE
유저 마이페이지 통계 기능 구현

### ISSUE THREAD

**Issue by street62** [Nexters/keyme-backend#65]
### Description
각 유저의 마이페이지에서 보여지는 성격 통계 기능을 구현합니다.

### Tasks
- [ ] 문제 풀이 제출 시 통계에 반영되도록 하는 EventHandler 로직 작성
- [ ] 유저 문제별 점수 통계 일괄처리 서비스 구현
- [ ] 유저별 통계 조회 서비스 구현
