### ISSUE TITLE
통합 예외처리 및 커스텀 에러코드 정리

### ISSUE THREAD

**Issue by RokwonK** [Nexters/keyme-backend#9]
### Description
글로벌 예외처리 핸들러 작성, 커스텀 common 예외 정리, 에러코드 및 에러코드별 description 정리 

### Tasks
- [x] 글로벌 예외처리 핸들러 셋팅
- [x] common 예외 정리
- [x] 에러코드별 description 정리
