### ISSUE TITLE
API 응답형식 변경

### ISSUE THREAD

**Issue by RokwonK** [Nexters/keyme-backend#93]
### Description
클라이언트 요청에 따라 API 응답형식을 변경합니다.

### Tasks
- [ ] 마이페이지 통계 형식 변경 (키네임 question -> questionStatistics)
- [ ] quesetion category(키네임 imageUrl -> iconUrl)
- [ ] question statistics(averageScore -> avgScore)
- [ ] question scorelist(hasNext 필드 추가)
